content/_index.md
content/getting_started/_index.md
content/getting_started/install-emedge.md
content/getting_started/subscribe-cvs.md

This reverts commit b2d54f3463340fe0cf847176ba2f5485e54a5f73.

Revert "many changes"

---

content/security/vulnerabilities.md

@soonseah Please review and approve. I removed the collapsible list on the Product fixes.

Make Product Fixes not collapsible

---

content/security/_index.md

changed security folder's weight and moved it to the bottom of the menu

Move security folder to the bottom of the menu

---

content/cloud_vista/overview/_index.md
content/cloud_vista/overview/homepage.md
content/cloud_vista/overview/inframonitoring/_index.md
content/cloud_vista/overview/inframonitoring/customize/_index.md
content/cloud_vista/overview/inframonitoring/customize/customizedatabase.md
content/cloud_vista/overview/inframonitoring/customize/customizescript.md
content/cloud_vista/overview/inframonitoring/customize/customizesnmp.md
content/cloud_vista/overview/inframonitoring/customize/customizethreshold.md
content/cloud_vista/overview/inframonitoring/discovering/_index.md
content/cloud_vista/overview/inframonitoring/discovering/discoverdevice.md
content/cloud_vista/overview/inframonitoring/editsettings.md
content/cloud_vista/overview/inframonitoring/monitoralerts.md
content/cloud_vista/overview/inframonitoring/monitordevices.md
content/cloud_vista/overview/inframonitoring/thresholdsettings.md
content/cloud_vista/overview/left_navigation.md
content/cloud_vista/overview/top_navigation.md

Changed links from Overview to overview as pages / images were not able to load

Changed links from Overview to overview

---

content/cloud_vista/_index.md
content/cloud_vista/alerts/_index.md
content/cloud_vista/apm/_index.md
content/cloud_vista/bizviews/_index.md
content/cloud_vista/loganalytics/_index.md
content/cloud_vista/maps/_index.md
content/cloud_vista/metrics/_index.md
content/cloud_vista/ncm/_index.md
content/cloud_vista/netflow/_index.md
content/cloud_vista/securityanalytics/_index.md
content/security/_index.md

Edited the Menu hierarchy, made security standalone and not under cloud vista

Rearranged Menu based on James feedback

---

content/_index.md
content/cloud_vista/_index.md
content/getting_started/_index.md

Edited spelling error for home page and getting started

Edited spelling error on Home page and getting started

---

config_netgain.yaml
config_spog.yaml

Edited URL links for Terms of Use and Privacy Policy for both NetGain and spog.ai

Edited URL links for spog.ai and Netgain

---

content/getting_started/emedge/_index.md
content/getting_started/spogportal.md

Added placeholder text for spog portal and corrected grammar error for emedge

Added placeholder text for spog portal and corrected grammar error

---

content/_index.md

added content for feedback paragraph in home page

edited feedback paragraph in home

---

content/getting_started/emedge/installation.md

to hide the windows_emedge installation at the emedge installation page

albert_23Jul

---

content/_index.md
content/getting_started/architecture.md

Added content based on PPT sent by Matthew, Changed spog.ai to more generic name "Architecture"

Added content for Home page and renamed spog.ai to Architecture

---

content/_index.md

Edited company name {{% company %}} in home page and added scroll function when in mobile view

Added scroll function for mobile view in home page

---

content/getting_started/emedge/Metricbeat/_index.md
content/getting_started/emedge/Metricbeat/installation.md
content/getting_started/emedge/_index.md
content/getting_started/emedge/emedge-agent/_index.md
content/getting_started/emedge/emedge-agent/config_checks/_index.md
content/getting_started/emedge/emedge-agent/config_checks/files.md
content/getting_started/emedge/emedge-agent/config_checks/processes.md
content/getting_started/emedge/emedge-agent/config_checks/scripts.md
content/getting_started/emedge/emedge-agent/config_checks/winsvc.md
content/getting_started/emedge/emedge-agent/installation.md

albert_17Aug

---

content/getting_started/emedge-agent/_index.md

albert_18Aug

---

content/security/Log4j2/_index.md

albert_13Dec2021

---

content/security/Log4j2/_index.md

albert_14Dec2021_am

---

content/security/Log4j2/_index.md

minor change on words spelling ang grammar

albert_14Dec2021_pm

---

content/security/Log4j2/_index.md

update with latest CVE-2021-45046

albert_16Dec_2021

---

content/news/Release/_index.md
content/news/_index.md

albert_06122022

---

content/news/Release/_index.md

albert_07012022

---

content/news/Release/_index.md

This request for release note update. Please help review and accept.

Paiboon_27Feb2022-update_release_log

---

content/news/Release/_index.md

Hi K.SS,
Please help review and accept this request for update patch release log.
Paiboon N.

Paiboon_31Mar2022-update_release_log

---

content/news/Release/_index.md

Hi K.SS,
This request for update release log v11.2.276. Please review and approve.
Thanks
Paiboon N.

Paiboon_14Jul2022-update_release_log

---

content/news/Release/_index.md

Hi K.SS,
I update for new patch release. Please review and approve krub.
Regards,
Paiboon N.

Paiboon_13Sep2022-update_release_log

---

content/news/Release/_index.md

Hi K.SS,
I already remove "TSS". Please review and accept krub.
Thanks
Paiboon N.

Paiboon_16Nov2022-update_release_log
